### ISSUE TITLE
error with op argmax

### ISSUE THREAD

**Issue by tianxiao-baai** [FlagOpen/FlagGems#124]
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/a7422532-620a-4569-8de4-3df3f75c3c84">

**Comment by tongxin** [comment]
Thanks, we'll look into it.

**Comment by tongxin** [comment]
Could you provide us a reproduce test case? Thanks.

**Comment by iclementine** [comment]
It is the problem that the max memory offset used to index the tensor exceeds the maximum value of int32. I am fixing it with int64 indexing when needed.

Also, reduction kernel with tile size equals next power of 2 to the size of the reduction axis is problematic, since it may exceed the max tensor numel of triton. So a loop along the reduction axis is added.

**Comment by tianxiao-baai** [comment]
The new code no longer reports any errors, so close this issue.
